name: Deploy Web Server and Upload to S3

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      # Step 3: Configure AWS Credentials using Access Key and Secret Key
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      # Step 4: Debug Directory Structure
      - name: Debug Directory Structure
        run: |
          echo "Listing repository structure..."
          ls -la
          echo "Checking for package.json..."
          find . -name "package.json"

      # Step 5: Install Dependencies (if `package.json` exists)
      - name: Install dependencies
        if: success()
        run: |
          echo "Installing dependencies..."
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No package.json file found. Skipping dependencies installation."
          fi

      # Step 6: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 7: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 8: Terraform Apply (Deploy Infrastructure)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 9: Build the application (if required)
      - name: Build application
        if: success()
        run: |
          echo "Building application..."
          if [ -d "build" ]; then
            npm run build
          else
            echo "Build directory not found. Skipping build step."
          fi

      # Step 10: Debug Build Directory
      - name: Debug Build Directory
        run: |
          echo "Listing build directory contents..."
          ls -la ./build || echo "Build directory not found."

      # Step 11: Upload build files to S3
      - name: Upload files to S3
        run: |
          echo "Uploading files to S3..."
          if [ -d "./build" ]; then
            aws s3 cp ./build/ s3://bhootni/ --recursive
          else
            echo "Build directory not found. Skipping S3 upload."
          fi

      # Step 12: Verify the deployment (List S3 Bucket contents to verify upload)
      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          aws s3 ls s3://bhootni/
