name: Deploy Web Server and Upload to S3

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      # Step 3: Configure AWS Credentials using Access Key and Secret Key
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "AWS credentials configured."

      # Step 4: Set private key for SSH from GitHub Secrets
      - name: Set private key for SSH
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > bhoot.pem
          chmod 600 bhoot.pem

      # Step 5: Install Dependencies (Optional, if needed)
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      # Step 6: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 7: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 8: Terraform Apply (Deploy Infrastructure)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 9: Build the application (if required)
      - name: Build application
        run: |
          echo "Building application..."
          npm run build

      # Step 10: Upload build files to S3 bucket
      - name: Upload files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Uploading files to S3..."
          aws s3 cp ./build/ s3://bhootni/ --recursive

      # Step 11: Verify the deployment (List S3 Bucket contents to verify upload)
      - name: Verify Deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Verifying deployment..."
          aws s3 ls s3://bhootni/
