name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Infrastructure and Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::120569613442:role/my_oidc_for_github_action
          role-session-name: GitHubActionsOIDC
          aws-region: us-east-1

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build the application
        run: |
          echo "Building application..."
          npm run build  # Replace with your actual build command

      - name: Upload files to S3
        run: |
          echo "Uploading files to S3..."
          aws s3 cp ./build/ s3://bhootni/ --recursive  # Replace with your build directory

      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          aws s3 ls s3://bhootni/
